// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ScanNetwork(arg1:main.ScanRange):Promise<void>;
export function GetScanHistory():Promise<main.ScanHistoryItem[]>;
