// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ScanNetwork(arg1) {
  return window['go']['main']['App']['ScanNetwork'](arg1);
}

export function GetScanHistory() {
  return window['go']['main']['App']['GetScanHistory']();
}

export function StartMonitoring(hostsToMonitor, searchHidden, hiddenPortsList) {
  return window['go']['main']['App']['StartMonitoring'](hostsToMonitor, searchHidden, hiddenPortsList);
}

export function StopMonitoring() {
  return window['go']['main']['App']['StopMonitoring']();
}

export function IsMonitoringActive() {
  return window['go']['main']['App']['IsMonitoringActive']();
}
